import os


mysql_username = os.getenv("MYSQL_USERNAME")
mysql_password = os.getenv("MYSQL_PASSWORD")
mysql_host = os.getenv("MYSQL_HOST")
mysql_port = os.getenv("MYSQL_PORT") or 3306
MYSQL_URI = f"mysql://{mysql_username}:{mysql_password}@{mysql_host}:{mysql_port}/everymarket"


DOWNLOADER_CLIENT_TLS_CIPHERS = "RSA+AES:RSA+3DES:RSA+AESGCM:ECDH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:ECDH+HIGH:DH+HIGH:DH+3DES:RSA+HIGH:DH+AES:ECDH+3DES:!aNULL:!eNULL:!MD5"

ELASTICSEARCH_SERVERS = os.getenv("ELASTICSEARCH_SERVERS", "35.192.187.156:80")
ELASTICSEARCH_USERNAME = os.getenv("ELASTICSEARCH_USERNAME")
ELASTICSEARCH_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")
ELASTICSEARCH_TIMEOUT = int(os.getenv("ELASTICSEARCH_TIMEOUT", 60))
ELASTICSEARCH_MAX_RETRY = int(os.getenv("ELASTICSEARCH_MAX_RETRY", 3))


WEBSHARE_USER = os.getenv("WEBSHARE_USER")
WEBSHARE_PASSWORD = os.getenv("WEBSHARE_PASSWORD")
WEBSHARE_COUNTRY = os.getenv("WEBSHARE_COUNTRY", "US")
